### PR TITLE
fix: suci profile B decryptSharedKey front zero truncated

### LINKED ISSUE #39: Decryption of MAC failed for Profile B
During one of our tests with free5gc, we noticed that the free5gc UDM failed to register a UE because of a MAC verification error. We used IMSI 001010123456789 with Home network key ID 2 and the Profile B SUCI encryption scheme. The error logs are below:

```
udm  | 2024-08-15T15:20:40.960487817Z [INFO][UDM][Main] UDM version:  
udm  | 	free5GC version: v3.4.1
udm  | 	build time:      2024-03-28T06:49:15Z
udm  | 	commit hash:     791b4688
udm  | 	commit time:     2024-03-27T16:13:12Z
udm  | 	go version:      go1.18.10 linux/amd64
udm  | 2024-08-15T15:20:40.960606030Z [INFO][UDM][CFG] Read config from [/free5gc/config/udmcfg.yaml]
udm  | 2024-08-15T15:20:40.963004747Z [INFO][UDM][Main] Log enable is set to [true]
udm  | 2024-08-15T15:20:40.963036621Z [INFO][UDM][Main] Log level is set to [info]
udm  | 2024-08-15T15:20:40.963044157Z [INFO][UDM][Main] Report Caller is set to [false]
udm  | 2024-08-15T15:20:40.963052779Z [INFO][UDM][Init] UDM Config Info: Version[1.0.3] Description[UDM initial local configuration]
udm  | 2024-08-15T15:20:40.963059764Z [INFO][UDM][Init] Server started
udm  | 2024-08-15T15:20:40.963231927Z [INFO][UDM][Util] udmconfig Info: Version[1.0.3] Description[UDM initial local configuration]
udm  | 2024-08-15T15:20:41.724724507Z [INFO][UDM][Main] OAuth2 setting receive from NRF: false
udm  | 2024-08-15T15:20:51.337572820Z [INFO][UDM][UEAU] Handle GenerateAuthDataRequest
udm  | 2024-08-15T15:20:51.337630832Z [INFO][UDM][Suci] suciPart: [suci 0 001 01 0 2 2 03A7B1DB2A9DB9D44112B59D03D8243DC6089FD91D2ECB78F5D16298634682E94373888B22BDC9293D1681922E17]
udm  | 2024-08-15T15:20:51.337639301Z [INFO][UDM][Suci] scheme 2
udm  | 2024-08-15T15:20:51.337646058Z [INFO][UDM][Suci] SUPI type is IMSI
udm  | 2024-08-15T15:20:51.337652332Z [INFO][UDM][Suci] SuciToSupi Profile B
udm  | 2024-08-15T15:20:51.337998057Z [ERRO][UDM][Suci] decryption MAC failed
udm  | 2024-08-15T15:20:51.338007343Z [ERRO][UDM][UEAU] suciToSupi error:  decryption MAC failed
udm  | 2024-08-15T15:20:51.338228623Z [INFO][UDM][GIN] | 403 |   10.100.200.13 | POST    | /nudm-ueau/v1/suci-0-001-01-0-2-2-03A7B1DB2A9DB9D44112B59D03D8243DC6089FD91D2ECB78F5D16298634682E94373888B22BDC9293D1681922E17/security-information/generate-auth-data |
```

I did some research about the problem and I suspect that the problem I encountered above is a bug in the Profile B decryption function `profileB` in `suci.go`. I have added the following test data to `suci_test.go`:

```
testCases := []struct {
		suci         string
		expectedSupi string
		expectedErr  error
}{
               ...
              {
			suci:         "suci-0-001-01-0-2-2-03a7b1db2a9db9d44112b59d03d8243dc6089fd91d2ecb78f5d16298634682e94373888b22bdc9293d1681922e17",
			expectedSupi: "imsi-001010123456789",
			expectedErr:  nil,
		},
}
```

When debugging the `profileB` function, I noticed that the `decryptSharedKey` that the free5gc UDM computes is:

```0xdcf8b5e1f91d9268c65a2942e68513b091b45425d21707f8b4ca4a1214b1e6```

whereas actually, the shared key here should be (the same value with 0x00 prepended):

```0x00dcf8b5e1f91d9268c65a2942e68513b091b45425d21707f8b4ca4a1214b1e6```

I suspect that the `big.Int` Go class automatically truncates 0 bytes in front of the number. In very specific cases, where the first x bytes of the shared key are equal to `0x00`, the free5gc UDM fails to decrypt the cipher text correctly and returns a MAC error.

### PR DESCRIPTION
**Pull request by a3828162**
- closes #39

### CODE REVIEW

**Review by andy89923 — APPROVED** [review]

File: pkg/suci/suci.go [hunk 1]
```diff
@@ -290,15 +290,16 @@ func profileB(input, supiType, privateKey string) (string, error) {
 	}
 
 	// x-coordinate is the shared key
-	decryptSharedKey, _ := elliptic.P256().ScalarMult(xUncompressed, yUncompressed, bHNPriv)
-	// fmt.Printf("deShared: %x\n", decryptSharedKey.Bytes())
+	decryptSharedKeyTmp, _ := elliptic.P256().ScalarMult(xUncompressed, yUncompressed, bHNPriv)
+	decryptSharedKey := FillFrontZero(decryptSharedKeyTmp, len(xUncompressed.Bytes()))
+	// fmt.Printf("deShared: %x\n", decryptSharedKey)
```
Comment (ianchen0119) [inline pkg/suci/suci.go:295]: remove unused code

Comment (a3828162) [reply pkg/suci/suci.go]: fix
